// ``GlyphList``의 서브셋 테이블 데이터. 파일 분리는 순수 조직적 이유(파일 길이 제한,
// M4 설계 §7 말미)이며, 타입·의미는 `GlyphList.swift`와 동일하다.

extension GlyphList {
  /// 이름 → 유니코드 문자열 서브셋(~400엔트리 목표). ``Encodings+Tables.swift``가 생산하는
  /// 모든 글리프 이름(ASCII + WinAnsi/MacRoman 고역)을 포함해 조회가 항상 성공하게 한다.
  static let table: [String: String] = [
    "space": " ", "exclam": "!", "quotedbl": "\"", "numbersign": "#", "dollar": "$",
    "percent": "%", "ampersand": "&", "quotesingle": "'", "parenleft": "(",
    "parenright": ")", "asterisk": "*", "plus": "+", "comma": ",", "hyphen": "-",
    "period": ".", "slash": "/", "zero": "0", "one": "1", "two": "2", "three": "3",
    "four": "4", "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
    "colon": ":", "semicolon": ";", "less": "<", "equal": "=", "greater": ">",
    "question": "?", "at": "@", "bracketleft": "[", "backslash": "\\",
    "bracketright": "]", "asciicircum": "^", "underscore": "_", "grave": "`",
    "braceleft": "{", "bar": "|", "braceright": "}", "asciitilde": "~",
    "quoteright": "\u{2019}", "quoteleft": "\u{2018}", "quotedblleft": "\u{201C}",
    "quotedblright": "\u{201D}", "quotesinglbase": "\u{201A}", "quotedblbase": "\u{201E}",
    "bullet": "\u{2022}", "ellipsis": "\u{2026}", "dagger": "\u{2020}",
    "daggerdbl": "\u{2021}", "circumflex": "\u{02C6}", "perthousand": "\u{2030}",
    "Scaron": "\u{0160}", "scaron": "\u{0161}", "guilsinglleft": "\u{2039}",
    "guilsinglright": "\u{203A}", "OE": "\u{0152}", "oe": "\u{0153}", "Zcaron": "\u{017D}",
    "zcaron": "\u{017E}", "endash": "\u{2013}", "emdash": "\u{2014}", "tilde": "\u{02DC}",
    "trademark": "\u{2122}", "Ydieresis": "\u{0178}", "Euro": "\u{20AC}",
    "exclamdown": "\u{00A1}", "cent": "\u{00A2}", "sterling": "\u{00A3}",
    "currency": "\u{00A4}", "yen": "\u{00A5}", "brokenbar": "\u{00A6}",
    "section": "\u{00A7}", "dieresis": "\u{00A8}", "copyright": "\u{00A9}",
    "ordfeminine": "\u{00AA}", "guillemotleft": "\u{00AB}", "logicalnot": "\u{00AC}",
    "registered": "\u{00AE}", "macron": "\u{00AF}", "degree": "\u{00B0}",
    "plusminus": "\u{00B1}", "twosuperior": "\u{00B2}", "threesuperior": "\u{00B3}",
    "acute": "\u{00B4}", "mu": "\u{00B5}", "paragraph": "\u{00B6}",
    "periodcentered": "\u{00B7}", "cedilla": "\u{00B8}", "onesuperior": "\u{00B9}",
    "ordmasculine": "\u{00BA}", "guillemotright": "\u{00BB}", "onequarter": "\u{00BC}",
    "onehalf": "\u{00BD}", "threequarters": "\u{00BE}", "questiondown": "\u{00BF}",
    "Agrave": "\u{00C0}", "Aacute": "\u{00C1}", "Acircumflex": "\u{00C2}",
    "Atilde": "\u{00C3}", "Adieresis": "\u{00C4}", "Aring": "\u{00C5}", "AE": "\u{00C6}",
    "Ccedilla": "\u{00C7}", "Egrave": "\u{00C8}", "Eacute": "\u{00C9}",
    "Ecircumflex": "\u{00CA}", "Edieresis": "\u{00CB}", "Igrave": "\u{00CC}",
    "Iacute": "\u{00CD}", "Icircumflex": "\u{00CE}", "Idieresis": "\u{00CF}",
    "Eth": "\u{00D0}", "Ntilde": "\u{00D1}", "Ograve": "\u{00D2}", "Oacute": "\u{00D3}",
    "Ocircumflex": "\u{00D4}", "Otilde": "\u{00D5}", "Odieresis": "\u{00D6}",
    "multiply": "\u{00D7}", "Oslash": "\u{00D8}", "Ugrave": "\u{00D9}",
    "Uacute": "\u{00DA}", "Ucircumflex": "\u{00DB}", "Udieresis": "\u{00DC}",
    "Yacute": "\u{00DD}", "Thorn": "\u{00DE}", "germandbls": "\u{00DF}",
    "agrave": "\u{00E0}", "aacute": "\u{00E1}", "acircumflex": "\u{00E2}",
    "atilde": "\u{00E3}", "adieresis": "\u{00E4}", "aring": "\u{00E5}", "ae": "\u{00E6}",
    "ccedilla": "\u{00E7}", "egrave": "\u{00E8}", "eacute": "\u{00E9}",
    "ecircumflex": "\u{00EA}", "edieresis": "\u{00EB}", "igrave": "\u{00EC}",
    "iacute": "\u{00ED}", "icircumflex": "\u{00EE}", "idieresis": "\u{00EF}",
    "eth": "\u{00F0}", "ntilde": "\u{00F1}", "ograve": "\u{00F2}", "oacute": "\u{00F3}",
    "ocircumflex": "\u{00F4}", "otilde": "\u{00F5}", "odieresis": "\u{00F6}",
    "divide": "\u{00F7}", "oslash": "\u{00F8}", "ugrave": "\u{00F9}", "uacute": "\u{00FA}",
    "ucircumflex": "\u{00FB}", "udieresis": "\u{00FC}", "yacute": "\u{00FD}",
    "thorn": "\u{00FE}", "ydieresis": "\u{00FF}", "fi": "\u{FB01}", "fl": "\u{FB02}",
    "dotlessi": "\u{0131}", "ring": "\u{02DA}", "breve": "\u{02D8}",
    "dotaccent": "\u{02D9}", "hungarumlaut": "\u{02DD}", "ogonek": "\u{02DB}",
    "caron": "\u{02C7}", "lessequal": "\u{2264}", "greaterequal": "\u{2265}",
    "notequal": "\u{2260}", "infinity": "\u{221E}", "partialdiff": "\u{2202}",
    "summation": "\u{2211}", "product": "\u{220F}", "pi": "\u{03C0}",
    "integral": "\u{222B}", "radical": "\u{221A}", "approxequal": "\u{2248}",
    "Delta": "\u{2206}", "Omega": "\u{03A9}", "lozenge": "\u{25CA}",
    "fraction": "\u{2044}", "florin": "\u{0192}"
  ]
}
